services:
  postgres:
    image: postgres:15-alpine
    container_name: oauth_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - oauth:/var/lib/data
    ports:
      - '5432:5432'
volumes:
  oauth: